### ISSUE TITLE
Push Notifications For Android Versions 7.1.1 and 6.0.1

### ISSUE THREAD

**Issue by clifton11221** [Xtraball/SiberianCMS#119]
Push Notifications don't appear to be delivered to phones with Android versions 7.1.1 and 6.0.1.

Siberian version 4.8.9.

**Comment by dbyzero** [comment]
We test on Android 6.0.1 without issues. We will test on 7.1.1.

**Comment by PofMagicfingers** [comment]
Tested in 7.1.1. Works without problems. I close this issue, please feel free to add additional details if you still have problems

**Comment by clifton11221** [comment]
Please check Germany and Asia.  The Android notifications don't appear to be working there.

**Comment by PofMagicfingers** [comment]
Hi! Notifications have nothing region/country specific. Android notifications works in the same way for any country or region. The same goes about iOS notifications. 

It might be an issue on client side, issue with notification service on the phone or a firewall or data provider not allowing traffic on GCM ports : http://stackoverflow.com/questions/15571576/which-port-and-protocol-does-google-cloud-messaging-gcm-use

Do you have the issues on multiple phones, multiple apps, including apps not created with siberian? Do you receive notifications sent to a siberian app on devices running another Android version or from another region/country? 

Please open a ticket if you own a commercial version of siberian, as this issue seems to be specific and doesn't affect all users.
