### ISSUE TITLE
Feature Weather (Yahoo) not working

### ISSUE THREAD

**Issue by grafixpress** [Xtraball/SiberianCMS#129]
Weather feature does not accept any location and data are empty. This is since quite a while. Maybe a change at Yahoo?

**Comment by rivman** [comment]
Same here. The unique API key (if used) already at 2000 requests ? Because I did see the weather working sometimes. Give us the possibility to use own par platform or / and individual yahoo API key. 

Thank you.

**Comment by clifton11221** [comment]
It needs to be made so that the API key is entered at the app level, not the admin level.  This way each app owner can have their own key and the admin won't go over the limit.

The same needs to be done for Maps, and YouTube.

**Comment by rivman** [comment]
Actually the limit is 2000 requests / Ip in one hour. So technically each user who use the app has 2000 requests to make in one ore (according to Siberian devs). The problem reside in module itself imo.

**Comment by fouineux** [comment]
The real problem seems to come from the public yahoo API... Sometimes we manage to retrieve some data, but most of the time the result is empty.

You can see the "bug" by using their console and refresh it multiples times : https://developer.yahoo.com/weather/

Most of the time, you have a null result.

I see that from March 2016 they forced OAuth, then turned back...

We'll do some tests with OAuth and update the weather module accordingly.

**Comment by PofMagicfingers** [comment]
@clifton11221 btw, Google Maps API key can now be set for each app, via the editor, in Settings -> Advanced. 

![capture d ecran 2017-01-26 a 14 43 54](https://cloud.githubusercontent.com/assets/469501/22333332/f81de526-e3d5-11e6-9797-204feec21b79.png)

**Comment by SiberianCMS** [comment]
The bug is gone by now, Yahoo removed their OAuth security on the Weather API.
Service is back to normal.
