### ISSUE TITLE
Dates in the inbox are incorrect

### ISSUE THREAD

**Issue by theeugenegroup** [Xtraball/SiberianCMS#164]
The dates of inbox messages all reflect the current date NOT the date they were sent

**Comment by krypt3d** [comment]
Hey,

Not sure if you noticed, there was another post similar to yours and Siberian is aware about it. 

https://github.com/Xtraball/SiberianCMS/issues/160

**Comment by SiberianCMS** [comment]
This will be patched/fixed in 4.8.12 along with Inbox 4.8.12

In fact, unless you set a date to "send the message on the specified date" the date will be  the current day.

The update will consist on guessing the old messages send date (with replies, etc ...) 

Then all the new inbox messages will have the good date saved
