### ISSUE TITLE
Local workspace does not work

### ISSUE THREAD

**Issue by karargaht** [Xtraball/SiberianCMS#17]
**"/local/design/desktop/backoffice/..." the path not working**

"sae/design/desktop/backoffice/..."using this path.

> "/local/design/desktop/siberian/..." the path is working

**Comment by alexyves** [comment]
Since 4.1.3 the cache system has been re-enabled, so if you make modifications in the "local" folder you have to clear "var/cache/design.cache" in order to make it working.

1. The cache is automatically cleared on each official Siberian update
2. We planned a new system page in the Backoffice for advanced usage, like clearing cache, etc ...

**Comment by karargaht** [comment]
I cleared cache and it worked. Thanks (:
