### ISSUE TITLE
Custom calendar events order

### ISSUE THREAD

**Issue by campoleo77** [Xtraball/SiberianCMS#225]
In the custom siberian calendar is possible to order the events from the closest to the farthest? The users want to see before the next event. If I insert many events the users to see the next must scrool down a list, not good. Thanks

**Comment by clifton11221** [comment]
I agree...

**Comment by clifton11221** [comment]
Yeah... I really see what you mean now.  There are a bunch of events listed in one of my client's apps and the ones that are coming up soon are all the way at the bottom of the list. 

So in order to see the events that about to come-up, the users have to scroll through the entire list of events.  Not very user friendly at all.

**Comment by dbyzero** [comment]
Thanks for the precision, can you provide a screenshot to be sure ?

**Comment by campoleo77** [comment]
![esempio](https://cloud.githubusercontent.com/assets/7079568/24246840/70ccf1fa-0fc9-11e7-9210-8c3995a36f96.JPG)
