### ISSUE TITLE
Fix missing radio and source code icons after install

### ISSUE THREAD

**Issue by MAWPRO** [Xtraball/SiberianCMS#3]
The radio and source code icons are missing once updating to 4.1 and gaining these new features
![siberiancms](https://cloud.githubusercontent.com/assets/6164966/15363709/6fe48b70-1cce-11e6-9dd1-38ca03b5085e.png)

**Comment by SiberianCMS** [comment]
Hello Mawpro,
I have some Questions:
How have you updated your siberiancms ? from the regular modules, or from github ?

**Comment by MAWPRO** [comment]
From the regular modules using backoffice

**Comment by SiberianCMS** [comment]
Ok I've found the issue the images were missing in the 4.1.0 update, this is planned to be fixed in the 4.1.1 update.

For now, you can pick up the icons in the repository here (as they are present in the full installer) https://github.com/Xtraball/SiberianCMS/tree/master/images/library
and upload them in the feature.

Thank you.
