### ISSUE TITLE
Feature: "Job" doesn't work

### ISSUE THREAD

**Issue by lampela** [Xtraball/SiberianCMS#349]
After creating the feature "Job" I try to create Companies or Categories, I can't . Nothing happens when I click the links. I've tried with 3 browsers, Safari, Firefox and Vivaldi. Same outcome.

PHP 5.6.31, JAVA version 1.8.0_131
Siberian 4.11.7

**Comment by Slicit** [comment]
Could you be more precise with screenshots for example! Thanks

**Comment by lampela** [comment]
<img width="676" alt="screen shot 2017-07-12 at 15 14 09" src="https://user-images.githubusercontent.com/7310492/28117132-daf27e2c-6714-11e7-990a-485cdc8f9702.png">

This is the scene that sticks there even if I click the Companies or Categories links. Nothing changes. So I can't add companies or categories.

**Comment by Slicit** [comment]
You are still using the old deprecated "Siberian" design, the new is "Flat"
Siberian design is deprecated and no more supported since January 1st 2017
However you can go in your backoffice and switch to the flat, as you are likely to encouter many bugs with this design

Go to **Backoffice > Appeareance > General** and switch to flat.

**Comment by lampela** [comment]
Wow - thank you for the quick help, works perfectly now!

**Comment by Slicit** [comment]
Perfect then, Enjoy the platform!
