### ISSUE TITLE
Realtime chat server error

### ISSUE THREAD

**Issue by karargaht** [Xtraball/SiberianCMS#356]
This is your demo site: http://demope.siberiancms.com/

![bbbb](https://user-images.githubusercontent.com/8930862/28248900-53b42afc-6a55-11e7-9664-20352662b630.png)

![aaa2](https://user-images.githubusercontent.com/8930862/28248899-53b2fb64-6a55-11e7-883e-befb47021fe6.png)

This is my site (PE - v4.11.7)

![aaa](https://user-images.githubusercontent.com/8930862/28248901-53b54126-6a55-11e7-8b13-2949ced5c9f7.png)

Socket.IO version 1.6

Realtime version: 1.4.1

With SSL or without SSL we get the same mistakes.

**Many people are experiencing these issues, please find a solution.**

**Comment by krypt3d** [comment]
Yeah it is not working even with the new update. Not only do I get the red error, it also creates weird chatrooms that dont go away. 

![img_1617](https://user-images.githubusercontent.com/25313885/28249655-1f0cf2c2-6a17-11e7-9eac-f96373fbc6a1.jpg)

**Comment by bluesnap-rock** [comment]
Try clearing all cache in backoffice

**Comment by karargaht** [comment]
I have names in the chat room. Only server is not working.
Names may be related to cache. Try to reinstall the module.
(After the server has not worked, the other faults are insignificant. The customer does not want to use the module.)

**Comment by bluesnap-rock** [comment]
Just try clearing cache....it wont effect users or chatrooms or names. This issue happened to me once I upgraded to the new chat module.....and I just cleared the cache and all was well.

**Comment by krypt3d** [comment]
Deleted cache, no luck unfortunately. Thank you for the recommendation.

**Comment by PofMagicfingers** [comment]
Hi,

Thanks for telling us about our demo install, we'll look into it, we might have forgotten to open some ports.

For your connection issue with the realtime chat module, here are the full requirements : 
- Socket.IO module should be installed
- Backoffice dashboard should show "SocketIO Server: Running" in External Extensions
- Port range 35500-36000 should be opened (one of this port is selected on server launch)
Use this command on linux system to open port range : 
 `iptables -I INPUT -p tcp -m multiport --dports 35500:36000 -j ACCEPT`
(this might be different depending on your system)
- If you have enabled HTTPS on your siberian backoffice : 
  - SSL certificates must be configured on your siberian backoffice : if you used our letsencrypt implementation, you have nothing to do, if you are using custom SSL, you must upload your certificates through your backoffice.
  - You must visit your application through HTTPS. As soon as you selected `Use HTTPS` in your backoffice, chatrooms will only works throught HTTPS. That's because the node server is only working either on HTTP, or HTTPS, never both.
  - Native application MUST be recompiled after you enabled Use HTTPS in backoffice.
- If you do not have enabled HTTPS in your backoffice : you should visit your application in using http only.

About github issues, 2 things : 
- This is a github project, not a forum. Please avoid jumping in conversation and talking about other issues if they're not exactly the same. Even if it's about the same part of the application. Chatroom names issue is absolutely not related to connection issue
- This is SiberianCMS SAE GitHub project. Real Time Chat is a paid module, including support for 1 year or lifetime. Please open a ticket using our support system or send us an email. GitHub should not be used for paid module support. 

Thanks.
