### ISSUE TITLE
Error upgrate from 4.12.10

### ISSUE THREAD

**Issue by Spotcloudtk** [Xtraball/SiberianCMS#441]
After updating to 4.12.10 you have problems with various javascripts, objects that do not load, inbox that does not send messages, cache does not erase, please check and correct the problem. Greetings

PS: With version 4.12.9 everything worked. apply update fixes 4.12.10, 4.12.11 and 4.12.12 and still will not work

**Comment by Slicit** [comment]
First update to 4.12.12 if not already done, then:

- Inbox not saving is known issue and will be fixed in the module update today.
- Cache does not erase, if you mean `Disk usage & Cache:` in the backoffice panel, yes it erases, but the disk size is fetched only a day (it's resource consuming so we moved it in cron every day to reduce server load)
- Various javascript issues, means almost nothing.

Now if you explain exactly the various javascript issues, i'll be glad to help you even more.

Thank you.

**Comment by Spotcloudtk** [comment]
Updated to the latest version 4.12.12 waiting for the ibox update.

Now neither qrcode nor promotion modules work.

**Comment by Spotcloudtk** [comment]
Do I have pagerappears on the server, affecting that?

**Comment by Vdvoem** [comment]
The guys just clear the cache system, all the rules work)

**Comment by Vdvoem** [comment]
The guys just clear the cache system, all the rules work )

**Comment by Spotcloudtk** [comment]
And this error?

(https://drive.google.com/file/d/0ByicUPK5lgwleDVGeWIzdGN2Rzg/view?usp=sharing)

(https://drive.google.com/file/d/0ByicUPK5lgwlRVRlN09LcUdOd3M/view?usp=sharing)

**Comment by Spotcloudtk** [comment]
ok. this update and fix work all now
